name: Web Test CI build
on:
  schedule:
    - cron: "0 0-23 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_job1:
    name: Web test

    build:
      env:
        PY_COLORS: "1"
      strategy:
        fail-fast: false
        max-parallel: 9
        matrix:
          os: [macos-latest]
          python-version: ["3.8"]

      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          pip install -r requirements.txt
      - name: Install allure
        run: |
          brew install allure
      - name: Run web test cases
        run: |
          python webtest_all.py
      - name: Generate allure web_test_report
        run: |
          allure generate web_test_report/ -o web_test_report/html --clean
      - name: Deploy web test allure report
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: web_test_report
